[logger]
level = "INFO"
#outputPath = "logs/app.log"
outputPath = "stdout"

[psql]
dsn = "host=postgres-container port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"

[server]
host = ""
port = "8081"

[db]
dbType = "sql"
#dbType = "memory"
