SchedulerInterval = 20
NotificationInterval = 30

[logger]
level = "INFO"
#outputPath = "logs/app.log"
outputPath = "stdout"

[rmq]
uri = "amqp://guest:guest@localhost:5672/"
exchange = "test-exchange-2"
exchangeType = "direct"
key = "test-key"
body = "foobar"
reliable = true
queue = 'test-2'

[psql]
dsn = "host=0.0.0.0 port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"

[db]
dbType = "sql"
#dbType = "memory"
