SchedulerInterval = 20
NotificationInterval = 30

[logger]
level = "INFO"
#outputPath = "logs/app.log"
outputPath = "stdout"

[rmq]
uri = "amqp://guest:guest@rabbit:5672/"
exchange = "test-exchange-2"
exchangeType = "direct"
key = "test-key"
body = "foobar"
reliable = true
queue = "test-2"

[psql]
dsn = "host=postgres-container port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"

[db]
dbType = "sql"
#dbType = "memory"
